# index.html.twig
index_page:
   path: /
   controller: App\Controller\MainController::index

user_logout:
  path: /user/logout
  controller: App\Controller\UserController::logout

user_profil:
  path: /user/profil
  controller: App\Controller\UserController::profilePage

user_profil_update:
  path: /user/profil/update
  controller: App\Controller\UserController::profileUpdate

admin_page:
  path: /admin/index
  controller: App\Controller\AdminController::admin

shop_page:
  path: /shop
  controller: App\Controller\ShopController::shop

shop_AddProduct_page:
  path: /shop/addProduct
  controller: App\Controller\ShopController::pageAddProduct

shop_AddProduct:
  path: /shop/addProduct/add
  controller: App\Controller\ShopController::addProduct

shop_DelProduct:
   path: /shop/delProduct/{id}
   controller: App\Controller\ShopController::delProduct