# index.html.twig
index_page:
   path: /
   controller: App\Controller\MainController::index

user_logout:
  path: /user/logout
  controller: App\Controller\UserController::logout

user_profil:
  path: /user/profil
  controller: App\Controller\UserController::profilePage

user_profil_update:
  path: /user/profil/update
  controller: App\Controller\UserController::profileUpdate

admin_page:
  path: /admin/index
  controller: App\Controller\AdminController::admin